version: '3'

services:
  nginix:
    image: nginx
    restart: always
    ports:
     - 80:80
    depends_on:
      - php
    links:
      - php
    volumes:
      - './nginx/dev.conf:/etc/nginx/conf.d/default.conf'
      - ./:/app
  php:
    build: .
    ports:
      - "9000:9000"
    #command: bash -c "chown -R www-data:www-data /app"
    volumes:
      - .:/app
  
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - MARIADB_USER=test
      - MARIADB_DATABASE=test
      - MARIADB_PASSWORD=test
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=test
    ports:
      - 3306:3306
    volumes:
      - data:/bitnami/mariadb


volumes:
  data:
    driver: local