version: '2'
services:
  
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - MARIADB_USER=test
      - MARIADB_DATABASE=wordpress
      - MARIADB_PASSWORD=test1234
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=test1234
    ports:
      - 3306:3306
    volumes:
      - wp_data:/bitnami/mariadb
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=test1234
      - WORDPRESS_DB_NAME=wordpress

volumes:
  wp_data:
    driver: local